- include_tasks: install_MacOSX.yaml
  when: ansible_distribution == "MacOSX"

- name: "include_tasks for ubuntu"
  fail:
    msg: "golang not currently supported for unix"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: "Setting up go paths"
  lineinfile:
    path: "{{ home_directory }}/.bash_modules/104.go.sh"
    line: "{{ item }}"
    create: "yes"
    mode: "600"
  loop:
    - "export GOROOT='{{ go_root }}'"
    - "export GOPATH='{{ go_path }}'"
    - 'export PATH="$GOPATH/bin:$GOROOT/bin:$PATH"'
