- hosts: "{{ host }}"
  roles:
  - role: "python"
  - role: "ripgrep"
  vars:
    username: "{{ docker_user | default(ansible_env.USER) }}"
    home_directory: >-
      {{
        "/Users"
        if ansible_distribution == 'MacOSX'
        else "/home"
      }}
