- hosts: "{{ host }}"
  roles:
  - role: "osx"
    when: ansible_distribution == "MacOSX"
  - role: "python"
  - role: "ripgrep"
  - role: "fzf"
  - role: "wormhole"
  vars:
    username: "{{ docker_user | default(ansible_env.USER) }}"
    home_prefix: >-
      {{
        "/Users"
        if ansible_distribution == 'MacOSX'
        else "/home"
      }}
    home_directory: "{{ home_prefix }}/{{ username }}"
