- include_tasks: install_MacOSX.yaml
  when: ansible_distribution == "MacOSX"

- include_tasks: install_Debian.yaml
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: "Installing virtualenv"
  block:
    - name: "Installing virtualenv"
      pip:
        name: virtualenv
        state: present
        executable: "{{ item }}"
      loop:
        # These should correspond to the Python versions installed
        - "{{ home_directory }}/pyenv/versions/3.7.10/bin/pip"
        - "{{ home_directory }}/pyenv/versions/3.8.9/bin/pip"
    - name: "Setting up pyenv shim"
      copy:
        src: "{{ home_directory }}/pyenv/shims/pip"
        dest: "{{ home_directory }}/pyenv/shims/virtualenv"
        remote_src: yes
